# Do not run if Values.externalConfigSecretName is set
{{- if not .Values.externalConfigSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-service.configSecretName" . }}
  labels:
    {{- include "demo-service.labels" . | nindent 4 }}
stringData:
  {{- with .Values.config }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}